name: jenkins-ecs-docker-build

env:
  IMAGE_NAME: aws-terraform-jenkins
  TAG:

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "main"
    paths:
      - "docker/*"
  pull_request:
    types:
      - closed
    branches:
      - "main"
    paths:
      - "docker/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform/jenkins-ecs

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Shorten Git SHA for Tagging
        run: echo GITHUB_SHA_SHORT=${GITHUB_SHA}|cut -c1-5>> $GITHUB_ENV
        #run: echo GITHUB_SHA_SHORT=${GITHUB_SHA} >> $GITHUB_ENV
        #echo "action_state=yellow" >> $GITHUB_ENV

      - name: Print test
        run: echo test

      - name: Print shortened SHA
        run: echo ${{ env.GITHUB_SHA_SHORT }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     file: ./docker/Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
